# Generated by Django 3.0.6 on 2020-05-22 13:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200522_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('dob', models.DateField(default=datetime.date.today, verbose_name='Date of Birth')),
                ('email', models.EmailField(blank=True, max_length=200)),
                ('currentresidentialtype', models.CharField(choices=[('HDB', 'HDB'), ('PE', 'PrivateEstate'), ('Condo', 'Condominium'), ('Campus', 'Campus Accomodation')], default='HDB', max_length=10)),
                ('gender', models.CharField(choices=[('Female', 'F'), ('Male', 'M')], max_length=10)),
                ('year_in_school', models.CharField(choices=[('FRESHMAN', 'Freshman'), ('SOPHOMORE', 'Sophomore'), ('JUNIOR', 'Junior'), ('SENIOR', 'Senior'), ('GRADUATE', 'Graduate')], default='FRESHMAN', max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='degree',
        ),
        migrations.DeleteModel(
            name='Degree',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
