# Generated by Django 3.0.1 on 2020-05-26 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200525_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='dob',
            field=models.DateField(help_text='yyyy-mm-dd', verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='email',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='portfolio_site',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
    ]
