# Generated by Django 3.0.1 on 2020-06-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200614_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='currentresidentialtype',
            field=models.CharField(choices=[('HDB', 'HDB'), ('PE', 'PrivateEstate'), ('Condo', 'Condominium'), ('Campus', 'Campus Accomodation')], default='HDB', max_length=10, verbose_name='Current Residential Type'),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='faculty',
            field=models.CharField(choices=[('ASS', 'Arts and Social Sciences'), ('BA', 'Business and Accountancy'), ('COM', 'Computing'), ('DENT', 'Dentistry'), ('SDE', 'Design and Environment'), ('ENG', 'Engineering'), ('LAW', 'Law'), ('MED', 'Medicine'), ('NUR', 'Nursing'), ('MUSIC', 'Music'), ('SCI', 'Science')], default='ASS', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='year_in_school',
            field=models.CharField(choices=[('FRESHMAN', 'Freshman'), ('SOPHOMORE', 'Sophomore'), ('JUNIOR', 'Junior'), ('SENIOR', 'Senior'), ('GRADUATE', 'Graduate')], default='FRESHMAN', max_length=10),
        ),
    ]
