# Generated by Django 3.0.1 on 2020-06-14 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200614_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='faculty',
            field=models.CharField(choices=[('Arts and Social Sciences', 'Arts and Social Sciences'), ('BA', 'Business and Accountancy'), ('COM', 'Computing'), ('DENT', 'Dentistry'), ('SDE', 'Design and Environment'), ('ENG', 'Engineering'), ('LAW', 'Law'), ('MED', 'Medicine'), ('NUR', 'Nursing'), ('MUSIC', 'Music'), ('SCI', 'Science')], default='ASS', max_length=50),
        ),
    ]
