# Generated by Django 3.0.1 on 2020-06-15 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20200614_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='singaporean',
            field=models.CharField(choices=[('Singaporean', 'Singaporean'), ('Non-Singaporean', 'Non-Singaporean')], default='Singaporean', max_length=50),
        ),
    ]
