# Generated by Django 3.0.6 on 2020-05-30 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surveytitle', models.CharField(max_length=100, verbose_name='Survey Title')),
                ('surveylink', models.URLField(verbose_name='Survey Link')),
                ('surveydescription', models.CharField(help_text='Include your survey dscription here!', max_length=5000, verbose_name='Survey Description')),
                ('surveytype', models.CharField(choices=[('EDN', 'Education'), ('HTC', 'Healthcare'), ('OTH', 'Others')], max_length=100, verbose_name='Survey Type')),
            ],
        ),
    ]
