# Generated by Django 3.0.1 on 2020-06-04 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadsurvey',
            name='surveytype',
        ),
        migrations.AddField(
            model_name='uploadsurvey',
            name='surveycategory',
            field=models.CharField(choices=[('EDN', 'Education'), ('HTC', 'Healthcare'), ('LFS', 'Lifestyle'), ('NUS', 'NUS-Related'), ('OTH', 'Others')], default='OTH', max_length=100, verbose_name='Survey Category'),
        ),
        migrations.AddField(
            model_name='uploadsurvey',
            name='uploadDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='uploadsurvey',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
