# Generated by Django 3.0.1 on 2020-06-07 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20200604_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadsurvey',
            name='additionaldetails',
            field=models.CharField(blank=True, default=False, max_length=5000, verbose_name='Additional Details'),
        ),
    ]
