# Generated by Django 3.0.6 on 2020-06-09 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0004_remove_uploadsurvey_additionaldetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadsurvey',
            name='user',
        ),
        migrations.AddField(
            model_name='uploadsurvey',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
