# Generated by Django 3.0.6 on 2020-06-09 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0005_auto_20200609_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadsurvey',
            name='creator',
        ),
        migrations.AddField(
            model_name='uploadsurvey',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
