# Generated by Django 3.0.6 on 2020-06-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_auto_20200609_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.CharField(choices=[('activated', 'Activated'), ('deactivated', 'Deactivated')], default='deactivated', max_length=12)),
            ],
        ),
    ]
