# Generated by Django 3.0.6 on 2020-06-16 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.AddField(
            model_name='uploadsurvey',
            name='is_completed',
            field=models.CharField(choices=[('completed', 'Completed'), ('uncompleted', 'Uncompleted')], default='uncompleted', max_length=12),
        ),
    ]
