# Generated by Django 3.0.1 on 2020-06-13 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_uploadsurvey_genderfilter'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenderFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender_filter', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='uploadsurvey',
            name='genderfilter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.GenderFilter'),
        ),
    ]
