# Generated by Django 3.0.1 on 2020-06-13 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_auto_20200613_0239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadsurvey',
            old_name='genderfilter',
            new_name='gender_filter',
        ),
    ]
