# Generated by Django 3.0.1 on 2020-06-13 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0010_auto_20200613_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadsurvey',
            name='gender_filter',
            field=models.ManyToManyField(blank=True, to='survey.GenderFilter'),
        ),
    ]
