# Generated by Django 3.0.1 on 2020-06-13 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0011_auto_20200613_0312'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_filter', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NationalityFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationality_filter', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ResidentialFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('residential_filter', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='YearFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_filter', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='uploadsurvey',
            name='faculty_filter',
            field=models.ManyToManyField(blank=True, to='survey.FacultyFilter'),
        ),
        migrations.AddField(
            model_name='uploadsurvey',
            name='nationality_filter',
            field=models.ManyToManyField(blank=True, to='survey.NationalityFilter'),
        ),
        migrations.AddField(
            model_name='uploadsurvey',
            name='residential_filter',
            field=models.ManyToManyField(blank=True, to='survey.ResidentialFilter'),
        ),
        migrations.AddField(
            model_name='uploadsurvey',
            name='year_filter',
            field=models.ManyToManyField(blank=True, to='survey.YearFilter'),
        ),
    ]
