# Generated by Django 3.0.1 on 2020-06-13 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0012_auto_20200613_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residentialfilter',
            name='residential_filter',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
