# Generated by Django 3.0.1 on 2020-06-15 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0013_auto_20200613_0353'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NationalityFilter',
            new_name='SingaporeanFilter',
        ),
        migrations.RenameField(
            model_name='singaporeanfilter',
            old_name='nationality_filter',
            new_name='singaporean_filter',
        ),
        migrations.RenameField(
            model_name='uploadsurvey',
            old_name='nationality_filter',
            new_name='singaporean_filter',
        ),
    ]
