# Generated by Django 3.0.6 on 2020-06-19 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_auto_20200617_0105'),
        ('survey', '0014_auto_20200615_0129'),
    ]

    operations = [
    ]
