# Generated by Django 3.0.1 on 2020-06-28 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0015_completedsurveys_reward_usereward_userpoints'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedeemedRewards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TotalPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='userpoints',
            name='user',
        ),
        migrations.AddField(
            model_name='reward',
            name='requiredpoints',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='reward',
            name='rewardtitle',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.DeleteModel(
            name='UseReward',
        ),
        migrations.DeleteModel(
            name='UserPoints',
        ),
        migrations.AddField(
            model_name='redeemedrewards',
            name='redeemedrewards',
            field=models.ManyToManyField(to='survey.Reward'),
        ),
        migrations.AddField(
            model_name='redeemedrewards',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
