# Generated by Django 3.0.6 on 2020-06-19 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0016_auto_20200620_0009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='completedsurveys',
            old_name='completedsurveys',
            new_name='completed',
        ),
    ]
