# Generated by Django 3.0.6 on 2020-06-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0017_auto_20200620_0016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedsurveys',
            name='completed',
        ),
        migrations.AddField(
            model_name='completedsurveys',
            name='completedsurveys',
            field=models.ManyToManyField(to='survey.UploadSurvey'),
        ),
    ]
