# Generated by Django 3.0.6 on 2020-07-11 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0018_auto_20200628_0503'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postedDate', models.DateField(default=django.utils.timezone.now)),
                ('subject', models.CharField(max_length=200, verbose_name='Report Subject')),
                ('details', models.CharField(help_text='Include your report details here!', max_length=10000, verbose_name='Report Details')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
