# Generated by Django 3.0.6 on 2020-06-19 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0019_auto_20200620_0330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rewardtitle', models.CharField(max_length=100, verbose_name='Title')),
                ('rewarddescription', models.CharField(max_length=5000, verbose_name='Reward Description')),
                ('reward_pic', models.ImageField(blank=True, upload_to='reward_pics')),
            ],
        ),
        migrations.CreateModel(
            name='UseReward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Reward')),
            ],
        ),
    ]
